language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_VERSION=1.8.12
  - DJANGO_VERSION=1.9.5

install: python
  - python setup.py -q install

after_success:
  - bash <(curl -s https://codecov.io/bash)
