sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=Django==1.8.15
  - DJANGO=Django==1.9.10
  - DJANGO=Django==1.10.2
branches:
  only:
    - master
install:
  - pip install -U pip wheel setuptools
  - python setup.py install
  - pip install DJANGO python-coveralls
script:
  - coverage run --source=rest_channels runtests.py
  - coverage report
addons:
  apt_packages:
    - pandoc
after_success:
  - coveralls