sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
branches:
  only:
    - master
install:
  - pip install tox-travis coveralls
script:
  - tox
  - coverage run --source=rest_channels runtests.py
  - coverage report
after_success:
  - coveralls