sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=Django==1.8.12
  - DJANGO=Django==1.9.5
branches:
  only:
    - master
install:
  - python setup.py install
  - pip install DJANGO python-coveralls
script:
  - coverage run --source=rest_channels runtests.py
  - coverage report
after_success:
  - coveralls