sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=Django==1.8.12
  - DJANGO=Django==1.9.5
branches:
  only:
    - master
install:
  - pip install DJANGO tox-travis
script:
  - tox
  - coverage run --source=rest_channels runtests.py
  - coverage report
after_success:
  - coveralls