sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install -U pip wheel setuptools python-coveralls tox tox-travis

script:
  - tox

addons:
  apt_packages:
    - pandoc

after_success:
  - coveralls
